### ISSUE TITLE
Aquí no se publica o sí se publica? creo que lo has puesto al reves??

### ISSUE THREAD

**Issue by lmagarin** [iesgrancapitan-llmm/mi-primera-pagina-web-luisperezcantarero#4]
https://github.com/iesgrancapitan-llmm/mi-primera-pagina-web-luisperezcantarero/blob/a9c2a808674dd377abf46ed2df737aa6971bb600/UD4/A2/feed.xml#L18

**Comment by luisperezcantarero** [comment]
Corregido

**Comment by luisperezcantarero** [comment]
Hecho [Commit](https://github.com/iesgrancapitan-llmm/mi-primera-pagina-web-luisperezcantarero/commit/d62801999a06d62d751ff461889c6b02f51405b1)
