### ISSUE TITLE
Sólo un artículo?? revisa todo lo que se solicita...

### ISSUE THREAD

**Issue by lmagarin** [iesgrancapitan-llmm/mi-primera-pagina-web-luisperezcantarero#5]
https://github.com/iesgrancapitan-llmm/mi-primera-pagina-web-luisperezcantarero/blob/a9c2a808674dd377abf46ed2df737aa6971bb600/UD4/A2/feed.xml#L29

- Los elementos obligatorios del canal. (Título, enlace y descripción)
- El enlace será el link de tu Github Pages (tarea UD3 A6. Mi sitio. Github pages).
- Categoría y autoría del canal.
- Idioma, fecha de última actualización y dirección de correo del alumno como administrador del canal.
- El canal no se actualizará los sábados y domingos. Y las horas de 00:00 a 5:00 horas
- Una imagen obtenida de Internet y que ilustre la temática del canal. Se puede subir la imagen a github o drive y utilizar el link de la imagen ya que no puede ser un link de un path de tu equipo. Si es de drive recuerda darle permisos.
- 4 artículos, como mínimo, con diferentes orígenes y los siguientes elementos.
  - Los elementos obligatorios del artículo.
  - Autor del artículo.
  - Un archivo multimedia que podrá ser vídeo, audio o imagen.
  - Fecha de publicación.
  - Fuente del artículo.

**Comment by luisperezcantarero** [comment]
Hecho

**Comment by luisperezcantarero** [comment]
Aqui está el [Commit](UD4/A2/feed.xml)

**Comment by luisperezcantarero** [comment]
Aquí está el [Commit](https://github.com/iesgrancapitan-llmm/mi-primera-pagina-web-luisperezcantarero/commit/b2904f081ab9419067568a082d643c619828267c)
