### ISSUE TITLE
Categoría y derechos del feed.

### ISSUE THREAD

**Issue by lmagarin** [iesgrancapitan-llmm/mi-primera-pagina-web-luisperezcantarero#6]
https://github.com/iesgrancapitan-llmm/mi-primera-pagina-web-luisperezcantarero/blob/b2fe0105b8713a85c0e3ce27e15ae94461f47f05/UD4/A3/feed.xml#L2

**Comment by luisperezcantarero** [comment]
Corregido [Categoria y derechos](https://github.com/iesgrancapitan-llmm/mi-primera-pagina-web-luisperezcantarero/blob/main/UD4/A3/feed.xml) del feed
